SET FOREIGN_KEY_CHECKS=0;
drop TABLE abstractionform;
drop TABLE agency;
drop TABLE appimage;
drop table batchbill;
drop TABLE billcomponent;
drop table billitem;
drop TABLE dbffile;
drop TABLE dysmorphologyexamination;
drop TABLE eyes;
drop TABLE face;
drop TABLE fee;
drop table growth;
drop table hair;
drop table head;
drop table designationlevel        ;
drop table contacttype        ;
drop table designationlevel        ;
drop table institutioncontact        ;
drop table institutionmonthsummery        ;
drop table institutionset        ;
drop table  item       ;
drop table  itembatch       ;
drop table  itemscategories       ;
drop table itemsdistributors        ;
drop table labtest        ;
drop table logins        ;
drop table manufacturingprocess        ;
drop table manufacturingprocesscycle        ;
drop table  manufacturingprocesscyclestock       ;
drop table manufacturingprocessinputoutput        ;
drop table notificationcategory        ;
drop table notificationform        ;
drop table payment        ;
drop table  paymentscheme       ;
drop table  personcontact       ;
drop table  personinstitution       ;
drop table  price       ;
drop table  record       ;
drop table  reorder       ;
drop table staff        ;
drop table  stockhistory       ;
drop table  transferhistory       ;
drop table  vtmsvmps       ;
SET FOREIGN_KEY_CHECKS=1;
